config/routes.rb
Rails.application.routes.draw do
  root to: "memo_accounts#index"

  resources :accounts, only: %w(index create show edit update)
  resources :transactions, only: %w(index new create edit update destroy) do
    collection do
      get :graph
    end
  end
  post "/transactions/:bank_transaction_id", to: "transactions#create", as: :create_transaction_from_bank_transaction
  post "/transactions/:bank_transaction_id/reconcile", to: "transactions#create_with_reconciliation", as: :reconcile_bank_transaction

  resources :bank_transactions, only: :index do
    member do
      get "/new-transaction", to: "transactions#new_from_bank_transaction", as: :new_transaction_from
    end
  end
  get "/bank_transactions/import",  to: "bank_transactions#new_import", as: :new_bank_transactions_import
  post "/bank_transactions/import", to: "bank_transactions#import", as: :bank_transactions_import

  resources :memo_accounts, only: %w(index show create)
  resources :reconciliations, except: %w(new edit)
  resources :liability_fundings, only: %w(index show new create)
  resources :revenues, only: %w(new create)
  resources :posting_rules
end

app/models/memo_account.rb
class MemoAccount < Sequel::Model
  unrestrict_primary_key

  def self.by_memo_account
    ds = MemoAccount.naked.
      join(TransactionMemo, [:memo_account]).
      group(:memo_account).
      select(:memo_account, Sequel.lit("count(distinct account)").as(:rowspan))

    MemoAccount.naked.
      left_join(TransactionMemo, [:memo_account]).
      left_join(Transaction, [:transaction_id]).
      left_join(ds, [:memo_account]).
      left_join(Account, [:account]).
      group(:memo_account_id, :account_id, :memo_account, :account, :rowspan).
      order{ [lower(memo_account), lower(account)] }.
      select{ [memo_account_id, account_id, memo_account, account, max(posted_on).as(:posted_on), (sum(amount_dt) - sum(amount_ct)).as(:balance), :rowspan] }.
      having(Sequel.lit("(sum(amount_dt) - sum(amount_ct)) <> 0")).
      select_append(Sequel.lit("row_number() over (partition by memo_account order by memo_account, account)").as(:row_number))
  end

  def self.by_account
    ds = MemoAccount.naked.
      join(TransactionMemo, [:memo_account]).
      group(:account).
      select(:account, Sequel.lit("count(distinct memo_account)").as(:rowspan))

    MemoAccount.naked.
      left_join(TransactionMemo, [:memo_account]).
      left_join(Account, [:account]).
      left_join(Transaction, [:transaction_id]).
      left_join(ds, [:account]).
      group(:memo_account_id, :account_id, :account, :memo_account, :rowspan).
      order{ [lower(account), lower(memo_account)] }.
      exclude(account: nil).
      having(Sequel.lit("(sum(amount_dt) - sum(amount_ct)) <> 0")).
      select{ [memo_account_id, account_id, account, memo_account, max(posted_on).as(:posted_on), (sum(amount_dt) - sum(amount_ct)).as(:balance), :rowspan] }.
      select_append(Sequel.lit("row_number() over (partition by account order by account, memo_account)").as(:row_number))
  end
end

app/controllers/memo_accounts_controller.rb
class MemoAccountsController < ApplicationController
  def index
    @memo_accounts_by_memo_account = MemoAccount.by_memo_account.to_a
    @memo_accounts_by_account = MemoAccount.by_account.to_a
    @accounts = Hash[*@memo_accounts_by_account.map{|row| [row.fetch(:account), row.fetch(:account_id)]}.uniq.flatten]
    @memo_accounts = Hash[*@memo_accounts_by_memo_account.map{|row| [row.fetch(:memo_account), row.fetch(:memo_account_id)]}.uniq.flatten]
  end

  def show
    @memo_account = MemoAccount[memo_account_id: params[:id]]
    raise "not found" unless memo_account

    @vm = MemoAccountTransactionsReport.new(params.fetch(:memo_account_transactions_report, {}).merge(memo_account: memo_account.memo_account))

    fixed_amount_posting_rule_entries_ds =
      FixedAmountPostingRuleEntry.
      join(PostingRule, [:posting_rule]).
      filter(memo_account: memo_account.memo_account).
      order{ lower(posting_rule) }.
      select{ [posting_rule_id, posting_rule, amount.as(:number)] }.select_append("amount".as(:rule))

    fixed_rate_posting_rule_entries_ds =
      FixedRatePostingRuleEntry.
      join(PostingRule, [:posting_rule]).
      filter(memo_account: memo_account.memo_account).
      order{ lower(posting_rule) }.
      select{ [posting_rule_id, posting_rule, rate.as(:number)] }.select_append("percentage".as(:rule))

    @posting_rule_entries = fixed_amount_posting_rule_entries_ds.to_a + fixed_rate_posting_rule_entries_ds.to_a
  end

  attr_reader :memo_account
  helper_method :memo_account
  private :memo_account
end

app/views/memo_accounts/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Envelopes</h1>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <ul class="tabs" data-tab>
      <li class="tab-title active"><a href="#by-account">par Compte</a></li>
      <li class="tab-title"><a href="#by-memo-account">par Envelope</a></li>
    </ul>
    <div class="tabs-content">
      <div class="content active" id="by-account">
      <% @accounts.each do |account, account_id| %>
        <h3><%= link_to account, account_url(account_id) %></h3>
        <table width="100%">
          <thead>
            <tr>
              <th>Envelope</th>
              <th>Dernière transaction</th>
              <th>Balance</th>
            </tr>
          </thead>
          <tbody>
          <% @memo_accounts_by_account.select{|row| row.fetch(:account) == account}.each do |row| %>
            <tr>
              <td><%= link_to row.fetch(:memo_account), memo_account_url(row.fetch(:memo_account_id)) %></td>
              <td class="posted_on"><%= row.fetch(:posted_on) ? l(row.fetch(:posted_on), format: :iso8601) : nil %></td>
              <td class="amount"><%= amount row.fetch(:balance) %></td>
            </tr>
          <% end %>
          </tbody>
          <% if @memo_accounts_by_account.select{|row| row.fetch(:account) == account}.size > 1 then %>
            <tfoot>
              <tr>
                <th scope="row" colspan="2">Total</th>
                <td class="amount">
                  <%= amount @memo_accounts_by_account.select{|row| row.fetch(:account) == account}.map{|row| row.fetch(:balance)}.reduce(&:+) %>
                </td>
              </tr>
            </tfoot>
          <% end %>
        </table>
      <% end %>
      </div>
      <div class="content" id="by-memo-account">
        <% @memo_accounts.each do |memo_account, memo_account_id| %>
          <h3><%= link_to memo_account, memo_account_url(memo_account_id) %></h3>
          <table width="100%">
            <thead>
              <tr>
                <th>Compte</th>
                <th>Dernière transaction</th>
                <th>Balance</th>
              </tr>
            </thead>
            <tbody>
            <% @memo_accounts_by_memo_account.select{|row| row.fetch(:memo_account) == memo_account}.each do |row| %>
              <tr>
                <td>
                  <% if row.fetch(:account) then %>
                    <%= link_to row.fetch(:account), account_url(row.fetch(:account_id)) %>
                  <% end %>
                </td>
                <td class="posted_on"><%= row.fetch(:posted_on) ? l(row.fetch(:posted_on), format: :iso8601) : nil %></td>
                <td class="amount"><%= amount row.fetch(:balance) %></td>
              </tr>
            <% end %>
            </tbody>
            <% if @memo_accounts_by_memo_account.select{|row| row.fetch(:memo_account) == memo_account}.size > 1 then %>
              <tfoot>
                <tr>
                  <th scope="row" colspan="2">Total</th>
                  <td class="amount">
                    <%= amount @memo_accounts_by_memo_account.select{|row| row.fetch(:memo_account) == memo_account}.map{|row| row.fetch(:balance)}.reduce(&:+) %>
                  </td>
                </tr>
              </tfoot>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/memo_accounts/show.html.erb
<div class="row">
  <%= datagrid_form_for vm, method: :get, url: memo_account_url(memo_account.memo_account_id) %>
  <%= paginate vm %>
  <%= datagrid_table vm, html: {width: "100%"}, order: false %>
  <%= paginate vm %>
</div>
<div class="row">
  <h3>Sources</h3>
  <% if @posting_rule_entries.any? then %>
    <ul>
      <% @posting_rule_entries.each do |entry| %>
        <li><%= link_to entry.posting_rule, edit_posting_rule_url(entry[:posting_rule_id]) %>: <%=  format_posting_rule_amount_or_percentage entry %></li>
      <% end %>
    </ul>
  <% else %>
    <p>Aucune règle de revenu n'ajoute de montants dans cette enveloppe.</p>
  <% end %>
</div>