config/routes.rb
Rails.application.routes.draw do
  root to: "memo_accounts#index"

  resources :accounts, only: %w(index create show edit update)
  resources :transactions, only: %w(index new create edit update destroy) do
    collection do
      get :graph
    end
  end
  post "/transactions/:bank_transaction_id", to: "transactions#create", as: :create_transaction_from_bank_transaction
  post "/transactions/:bank_transaction_id/reconcile", to: "transactions#create_with_reconciliation", as: :reconcile_bank_transaction

  resources :bank_transactions, only: :index do
    member do
      get "/new-transaction", to: "transactions#new_from_bank_transaction", as: :new_transaction_from
    end
  end
  get "/bank_transactions/import",  to: "bank_transactions#new_import", as: :new_bank_transactions_import
  post "/bank_transactions/import", to: "bank_transactions#import", as: :bank_transactions_import

  resources :memo_accounts, only: %w(index show create)
  resources :reconciliations, except: %w(new edit)
  resources :liability_fundings, only: %w(index show new create)
  resources :revenues, only: %w(new create)
  resources :posting_rules
end

app/models/liability_funding.rb
class LiabilityFunding < Sequel::Model
  one_to_many :entries, class: LiabilityFundingEntry, key: [:account, :funding_transaction_id]

  def entries=(rows)
    rows.each{|row| add_entry row}
  end
end

app/controllers/liability_fundings_controller.rb
class LiabilityFundingsController < ApplicationController
  def index
    @vm = LiabilityFundingReport.new
  end

  def show
    @vm = LiabilityFundingTransactionEntriesReport.new(account_id: params[:id])
  end

  def new
    account = Account[account_id: params[:account_id]]
    raise "not found" unless account

    @liability_funding = LiabilityFundingForm.new(LiabilityFunding.new(account: account.account))
    if @liability_funding.validate(params[:liability_funding]) then
      amount = TransactionEntry.naked.
        filter(transaction_id: @liability_funding.entries.map(&:transaction_id)).
        select{ sum(amount_ct).as(:amount) }.
        first.fetch(:amount)

      @vm = TransactionForm.new(
        Transaction.new(
          transaction_id: SecureRandom.uuid,
          posted_on: Date.today,
          booked_on: Date.today,
          description: "Remboursement de dettes sur carte de crédit",
          entries: 4.times.map{ TransactionEntry.new }.unshift(TransactionEntry.new(account: account.account, amount_dt: amount, amount_ct: BigDecimal(0))),
          memos: 30.times.map{ TransactionMemo.new }))
      render "transactions/new"
    else
      raise "TODO on error"
    end
  end

  attr_reader :bank_transaction
  helper_method :bank_transaction
end

app/views/liability_fundings/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Remboursement des crédits</h1>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <%= datagrid_form_for vm, method: :get, url: liability_fundings_url %>
    <%= datagrid_table vm, html: {width: "100%"}, order: false %>
  </div>
</div>

app/views/liability_fundings/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Rapport des dettes à rembourser</h1>
  </div>
</div>

<%= form_tag new_liability_funding_url, method: :get do %>
  <%= hidden_field_tag :account_id, vm.account_id %>
  <div class="row">
    <div class="small-12 columns">
      <%= datagrid_table vm, html: {width: "100%"}, order: false %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <%= button_tag "Rembourser", name: nil, class: "button primary" %>
    </div>
  </div>
<% end %>