config/routes.rb
Rails.application.routes.draw do
  root to: "memo_accounts#index"

  resources :accounts, only: %w(index create show edit update)
  resources :transactions, only: %w(index new create edit update destroy) do
    collection do
      get :graph
    end
  end
  post "/transactions/:bank_transaction_id", to: "transactions#create", as: :create_transaction_from_bank_transaction
  post "/transactions/:bank_transaction_id/reconcile", to: "transactions#create_with_reconciliation", as: :reconcile_bank_transaction

  resources :bank_transactions, only: :index do
    member do
      get "/new-transaction", to: "transactions#new_from_bank_transaction", as: :new_transaction_from
    end
  end
  get "/bank_transactions/import",  to: "bank_transactions#new_import", as: :new_bank_transactions_import
  post "/bank_transactions/import", to: "bank_transactions#import", as: :bank_transactions_import

  resources :memo_accounts, only: %w(index show create)
  resources :reconciliations, except: %w(new edit)
  resources :liability_fundings, only: %w(index show new create)
  resources :revenues, only: %w(new create)
  resources :posting_rules
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @vm = TransactionsReport.new({order: :posted_on}.merge(params[:transactions_report] || {}))
  end

  def graph
    graph_transactions_report = {
      posted_on: [30.days.ago.at_beginning_of_month, Date.today.at_beginning_of_month - 1].map(&:to_s),
    }

    @vm = GraphTransactionsReport.new(graph_transactions_report.merge(params[:graph_transactions_report] || {}))
  end

  def new
    @vm = TransactionForm.new(
      Transaction.new(
        transaction_id: SecureRandom.uuid,
        booked_on: Date.today,
        posted_on: Date.today,
        description: "",
        memos: TRANSACTION_MEMOS_AVAILABLE.times.map { TransactionMemo.new },
        entries: TRANSACTION_ENTRIES_AVAILBLE.times.map{ TransactionEntry.new }))
  end

  def create
    if params.has_key?(:liability_funding) then
      @liability_funding = LiabilityFundingForm.new(LiabilityFunding.new)
      raise "invalid liability_funding" unless @liability_funding.validate(params[:liability_funding])
    end

    @vm = TransactionForm.new(
      Transaction.new(
        transaction_id: SecureRandom.uuid,
        booked_on: Date.today,
        posted_on: Date.today,
        description: "",
        memos: TRANSACTION_MEMOS_AVAILABLE.times.map { TransactionMemo.new },
        entries: TRANSACTION_ENTRIES_AVAILBLE.times.map{ TransactionEntry.new }))
    if vm.validate(params[:transaction]) then
      vm.save do |hash|
        DB.transaction do
          transaction = Transaction.create(transaction_id: vm.transaction_id, booked_on: vm.booked_on, posted_on: vm.posted_on, description: vm.description)
          raise transactions.errors.full_messages.inspect unless transaction.persisted?

          vm.entries.delete_if{|entry| entry.amount_dt.blank? && entry.amount_ct.blank?}
          vm.entries.each{|entry| entry.amount_dt = BigDecimal(entry.amount_dt)}
          vm.entries.each{|entry| entry.amount_ct = BigDecimal(entry.amount_ct)}
          entries = vm.entries.map do |entry|
            [transaction.transaction_id, entry.account, entry.amount_dt.blank? ? BigDecimal(0) : entry.amount_dt, entry.amount_ct.blank? ? BigDecimal(0) : entry.amount_ct]
          end.reject{|row| row[2, 2].all?(&:zero?)}
          TransactionEntry.import([:transaction_id, :account, :amount_dt, :amount_ct], entries)
          if vm.bank_transaction_id.present? then
            ReconciledTransaction.create(
              transaction_id: transaction.transaction_id,
              bank_transaction_id: vm.bank_transaction_id,
              account: BankTransaction.naked.filter(bank_transaction_id: vm.bank_transaction_id).join(BankAccount, [:account_number_hash]).select_map(:account).first,
              reconciled_on: Date.today)
          end

          memos = vm.memos.reject{|entry| [entry.amount_dt, entry.amount_ct].all?(&:blank?)}.map do |memo|
            amount_dt = BigDecimal(memo.amount_dt)
            amount_ct = BigDecimal(memo.amount_ct)
            [transaction.transaction_id, memo.account, memo.memo_account, amount_dt, amount_ct]
          end
          TransactionMemo.import([:transaction_id, :account, :memo_account, :amount_dt, :amount_ct], memos)

          if @liability_funding then
            @liability_funding.model.funding_transaction_id = transaction.transaction_id
            @liability_funding.save
          end
        end
      end

      if @liability_funding then
        redirect_to liability_fundings_url, notice: "Reimbursement recorded successfully"
      elsif vm.bank_transaction_id.blank? then
        redirect_to transactions_url, notice: "Transaction recorded successfully"
      else
        redirect_to bank_transactions_url(
          :"bank_transactions_report[reconciled]" => "NO",
          :"bank_transactions_report[bank_account_id]" => BankTransaction.naked.filter(bank_transaction_id: vm.bank_transaction_id).join(BankAccount, [:account_number_hash]).select_map(:bank_account_id).first)
      end
    else
      render action: :new
    end
  rescue Sequel::UniqueConstraintViolation, Sequel::ForeignKeyConstraintViolation, Sequel::DatabaseError => e
    flash.now[:notice] = "#{e.class}: #{e.message}"
    render action: :new
  end

  def new_from_bank_transaction
    @bank_transaction = BankTransaction[bank_transaction_id: params[:id]]
    raise "not found" unless bank_transaction

    account = Account.join(BankAccount, [:account])[account_number_hash: bank_transaction.account_number_hash]
    raise "not found" unless account

    entry = TransactionEntry.new
    entry.account = account.account
    case account.kind
    when "asset", "revenue"
      if bank_transaction.amount < 0 then
        entry.amount_dt = 0
        entry.amount_ct = bank_transaction.amount.abs
      else
        entry.amount_dt = bank_transaction.amount.abs
        entry.amount_ct = 0
      end
    when "liability", "expense", "equity"
      if bank_transaction.amount < 0 then
        entry.amount_dt = bank_transaction.amount.abs
        entry.amount_ct = 0
      else
        entry.amount_dt = 0
        entry.amount_ct = bank_transaction.amount.abs
      end
    else
      raise "ASSERTION ERROR: Unrecognized account kind for #{account.inspect}"
    end

    @vm = TransactionForm.new(
      Transaction.new(
        booked_on: Date.today,
        posted_on: bank_transaction.posted_on,
        description: bank_transaction.description,
        memos: TRANSACTION_MEMOS_AVAILABLE.times.map { TransactionMemo.new },
        entries: TRANSACTION_ENTRIES_AVAILBLE.times.map{ TransactionEntry.new }.unshift(entry)))
    vm.account = account.account
    vm.bank_transaction_id = bank_transaction.bank_transaction_id

    @reconciliation_form = ProcessingForm.new(vm.model) if candidates(account.account).any?

    render action: :new
  end

  def create_with_reconciliation
    bank_transaction = BankTransaction[bank_transaction_id: params[:bank_transaction_id]]
    raise "not found" unless bank_transaction

    DB.transaction do
      model = ReconciledTransaction.create(
        bank_transaction_id: bank_transaction.bank_transaction_id,
        transaction_id: params[:transaction][:transaction_id],
        account: bank_transaction.account,
        reconciled_on: Date.today)
      raise "not saved" unless model.persisted?
    end

    redirect_to bank_transactions_url(
      :"bank_transactions_report[reconciled]" => "NO",
      :"bank_transactions_report[bank_account_id]" => BankTransaction.naked.filter(bank_transaction_id: bank_transaction.bank_transaction_id).join(BankAccount, [:account_number_hash]).select_map(:bank_account_id).first)
  end

  def edit
    transaction = Transaction[transaction_id: params[:id]]
    raise "not found" unless transaction

    @vm = TransactionForm.new(transaction)

    missing_entries =  3.times.map{ TransactionEntry.new }
    missing_memos   = TRANSACTION_MEMOS_AVAILABLE.times.map{ TransactionMemo.new  }
    vm.entries = vm.entries + missing_entries
    vm.memos   = vm.memos   + missing_memos
  end

  def update
    transaction = Transaction[transaction_id: params[:id]]
    raise "not found" unless transaction

    @vm = TransactionForm.new(transaction)
    if vm.validate(params[:transaction]) then
      vm.save do |_|
        DB.transaction do
          # Create a completely new transaction
          new_transaction = Transaction.create(transaction.values.merge(transaction_id: SecureRandom.uuid))
          transaction_id = new_transaction.transaction_id

          vm.entries.each{|entry| entry.amount_dt = BigDecimal(entry.amount_dt)}
          vm.entries.each{|entry| entry.amount_ct = BigDecimal(entry.amount_ct)}
          entries = vm.entries.reject{|entry| entry.account.blank? || (entry.amount_dt.zero? && entry.amount_ct.zero?)}.map do |entry|
            [transaction_id, entry.account, entry.amount_dt.blank? ? BigDecimal(0) : entry.amount_dt, entry.amount_ct.blank? ? BigDecimal(0) : entry.amount_ct]
          end
          TransactionEntry.import([:transaction_id, :account, :amount_dt, :amount_ct], entries)
          ReconciledTransaction.naked.filter(transaction_id: transaction.transaction_id).each do |reconciliation|
            # Recreate any reconciliation transactions, pointing to the new transaction
            if entries.any?{|entry| entry[1] == reconciliation.fetch(:account)} then
              ReconciledTransaction.create(reconciliation.merge(transaction_id: transaction_id))
            end
          end

          memos = vm.memos.map do |memo|
            [transaction_id, memo.account, memo.memo_account, memo.amount_dt.blank? ? BigDecimal(0) : BigDecimal(memo.amount_dt), memo.amount_ct.blank? ? BigDecimal(0) : BigDecimal(memo.amount_ct)]
          end.reject{|row| row[3, 2].all?(&:zero?)}
          TransactionMemo.import([:transaction_id, :account, :memo_account, :amount_dt, :amount_ct], memos)

          # Delete the existing transaction, including all associated models...
          transaction.delete

          # Only to recreate it, by renaming the new transaction!
          Transaction.
            filter(transaction_id: new_transaction.transaction_id).
            update(transaction_id: transaction.transaction_id)
        end
      end
      redirect_to transactions_url, notice: "Successfully saved transaction"
    else
      missing_entries = (TRANSACTION_ENTRIES_AVAILBLE - vm.entries.size).times.map{ TransactionEntry.new }
      missing_memos   = (TRANSACTION_MEMOS_AVAILABLE - vm.memos.size).times.map{ TransactionMemo.new  }
      vm.entries = vm.entries + missing_entries
      vm.memos   = vm.memos   + missing_memos
      render action: :edit
    end
  rescue Sequel::ForeignKeyConstraintViolation => e
    logger.info "#{e.class}: #{e.message}"
    flash.now[:error] =
      case e.message
      when /reconciliation_entries_transaction_id_fkey/
        match = e.message.match(/[(]([a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}), ([^,]+), ([^,]+), ([^,]+)[)]/)

app/views/transactions/_form.html.erb
  <div class="row">
    <div class="small-10 columns">
      <label class="<%= vm.errors.include?(:description) ? "error" : nil %>">Description de transaction
        <%= f.text_field :description, class: vm.errors.include?(:description) ? "error" : nil, autocomplete: "off" %>
        <% if vm.errors.include?(:description) %>
          <small class="error"><%= vm.errors.full_messages_for(:description).to_sentence %></small>
        <% end %>
      </label>
    </div>
    <div class="small-2 columns">
      <label>Date <%= f.text_field :posted_on, readonly: vm.posted_on_readonly?, autocomplete: "off" %></label>
    </div>
  </div>

  <div class="row">
    <div class="small-8 columns">
      <h4 id="label_account">Compte</h4>
    </div>
    <div class="small-2 columns">
      <h4 id="label_amount_dt">Montant DT</h4>
    </div>
    <div class="small-2 columns">
      <h4 id="label_amount_ct">Montant CT</h4>
    </div>
  </div>

  <%= f.fields_for :entries do |fentry| %>
    <div class="row">
      <div class="small-8 columns">
        <%= fentry.select :account, accounts_for_select, include_blank: true, :"aria-labelledby" => "label_account" %>
      </div>
      <div class="small-2 columns">
        <%= fentry.text_field :amount_dt, value: amount(fentry.object.amount_dt, delimiter: "", separator: "."), :"aria-labelledby" => "label_amount_dt", autocomplete: "off" %>
      </div>
      <div class="small-2 columns">
        <%= fentry.text_field :amount_ct, value: amount(fentry.object.amount_ct, delimiter: "", separator: "."), :"aria-labelledby" => "label_amount_ct", autocomplete: "off" %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="small-4 columns">
      <h4 id="label_account2">Compte</h4>
    </div>
    <div class="small-4 columns">
      <h4 id="label_memo_account">Envelope</h4>
    </div>
    <div class="small-2 columns">
      <h4 id="label_memo_amount_dt">Montant DT</h4>
    </div>
    <div class="small-2 columns">
      <h4 id="label_memo_amount_ct">Montant CT</h4>
    </div>
  </div>

  <% if vm.errors[:entries].present? then %>
    <div data-alert class="alert-box alert">
      <% vm.errors.full_messages_for(:entries).each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <%= f.fields_for :memos do |fmemo| %>
    <div class="row">
      <div class="small-4 columns">
        <%= fmemo.select :account, asset_accounts_for_select, include_blank: true, :"aria-labelledby" => "label_account2" %>
      </div>
      <div class="small-4 columns">
        <%= fmemo.select :memo_account, memo_accounts_for_select.map{|row| [row[1].zero? ? row[0] : "#{row[0]} (#{amount row[1]})", row[0]]}, include_blank: true, :"aria-labelledby" => "label_memo_account" %>
      </div>
      <div class="small-2 columns">
        <%= fmemo.text_field :amount_dt, :"aria-labelledby" => "label_memo_amount_dt", autocomplete: "off" %>
      </div>
      <div class="small-2 columns">
        <%= fmemo.text_field :amount_ct, :"aria-labelledby" => "label_memo_amount_ct", autocomplete: "off" %>
      </div>
    </div>
  <% end %>

  <% if vm.errors[:memos].present? then %>
    <div data-alert class="alert-box alert">
      <% vm.errors.full_messages_for(:memos).each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

app/views/transactions/_new_transaction.html.erb
<h1><%= t("transactions.new.tabs.new") %></h1>
<%= form_for vm, url: transactions_url do |f| %>
  <% if @liability_funding then %>
    <%= fields_for :liability_funding, @liability_funding do |funding_form| %>
      <%= funding_form.hidden_field :account %>
      <%= funding_form.fields_for :entries, @liability_funding.entries do |entry_form| %>
        <%= entry_form.hidden_field :transaction_id %>
      <% end %>
    <% end %>
  <% end %>
  <%= f.hidden_field :bank_transaction_id, value: bank_transaction.try(:bank_transaction_id) %>
  <%= render partial: "transactions/form", locals: {f: f} %>
  <div class="row">
    <div class="small-12 columns">
      <%= button_tag "Créer", class: "button success", name: nil %>
    </div>
  </div>
<% end %>

app/views/transactions/_reconciliation_form.html.erb
<h1><%= t("transactions.new.tabs.reconcile") %></h1>
<h2>
  <%= l bank_transaction.posted_on, format: :iso8601 %>
  <%= bank_transaction.description %>
</h2>
<%= form_for @reconciliation_form, url: reconcile_bank_transaction_url(bank_transaction_id: bank_transaction.bank_transaction_id) do |f| %>
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Posted On</th>
        <th>Description</th>
        <th>Amount DT</th>
        <th>Amount CT</th>
      </tr>
    </thead>
    <tbody>
    <% candidates(vm.account).each do |candidate| %>
      <tr>
        <td><%= f.radio_button :transaction_id, candidate.fetch(:transaction_id) %></td>
        <td><%= l candidate.fetch(:posted_on), format: :iso8601 %></td>
        <td><%= link_to candidate.fetch(:description), transaction_url(id: candidate.fetch(:transaction_id)) %></td>
        <td><%= amount candidate.fetch(:amount_dt) %></td>
        <td><%= amount candidate.fetch(:amount_ct) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="small-12 columns">
      <%= button_tag "Concilier", class: "button success", name: nil %>
    </div>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <%= link_to "Détruire", transaction_url(vm.transaction_id), method: :delete, class: "button warning right tiny" %>
    <h1>Modifier une transaction</h1>
  </div>
</div>
<%= form_for vm do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  <div class="row">
    <div class="small-12 columns">
      <%= button_tag "Enregistrer", class: "button success", name: nil %>
    </div>
  </div>
<% end %>

app/views/transactions/graph.html.erb
<div class="row">
  <%= datagrid_form_for vm, method: :get, url: graph_transactions_url %>
  <div class="large-12 columns">
    <div id="chart" style="width:100%; height:600px;"></div>
  </div>
</div>
<script>
$(function () {
    $("#chart").highcharts({
        chart: {
          type: "column"
        },
        title: {
          text: "Dépenses"
        },
        xAxis: {
          categories: <%= (vm.assets.to_a.select{|row| row.fetch(:account_kind) == "expense"}.map{|row| row.fetch(:account)} + vm.assets.to_a.select{|row| row.fetch(:account_kind) == "revenue"}.map{|row| row.fetch(:account)}).to_json.html_safe %>
        },
        yAxis: {
          title: {
            text: ""
          }
        },
        series: [{
          showInLegend: false,
          data: <%= (vm.assets.to_a.select{|row| row.fetch(:account_kind) == "expense"}.map{|row| (row.fetch(:amount_ct) - row.fetch(:amount_dt)).to_f} + vm.assets.to_a.select{|row| row.fetch(:account_kind) == "revenue"}.map{|row| (row.fetch(:amount_ct) - row.fetch(:amount_dt)).to_f}).to_json.html_safe %>
        }]
    });
});
</script>

app/views/transactions/index.html.erb
<div class="row">
  <%= datagrid_form_for vm, method: :get, url: transactions_url %>
  <%= paginate vm %>
  <%= datagrid_table vm, html: {width: "100%"}, order: false %>
  <%= paginate vm %>
</div>

app/views/transactions/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <% if @reconciliation_form then %>
      <ul class="tabs" data-tab>
        <li class="tab-title active"><%= link_to t("transactions.new.tabs.reconcile"), "#reconcile" %></li>
        <li class="tab-title"><%= link_to t("transactions.new.tabs.new"), "#new" %></li>
      </ul>
      <div class="tabs-content">
        <div class="content active" id="reconcile">
          <%= render partial: "reconciliation_form" %>
        </div>
        <div class="content" id="new">
          <%= render partial: "new_transaction" %>
        </div>
      </div>
    <% else %>
      <%= render partial: "new_transaction" %>
    <% end %>
  </div>
</div>