config/routes.rb
Rails.application.routes.draw do
  root to: "memo_accounts#index"

  resources :accounts, only: %w(index create show edit update)
  resources :transactions, only: %w(index new create edit update destroy) do
    collection do
      get :graph
    end
  end
  post "/transactions/:bank_transaction_id", to: "transactions#create", as: :create_transaction_from_bank_transaction
  post "/transactions/:bank_transaction_id/reconcile", to: "transactions#create_with_reconciliation", as: :reconcile_bank_transaction

  resources :bank_transactions, only: :index do
    member do
      get "/new-transaction", to: "transactions#new_from_bank_transaction", as: :new_transaction_from
    end
  end
  get "/bank_transactions/import",  to: "bank_transactions#new_import", as: :new_bank_transactions_import
  post "/bank_transactions/import", to: "bank_transactions#import", as: :bank_transactions_import

  resources :memo_accounts, only: %w(index show create)
  resources :reconciliations, except: %w(new edit)
  resources :liability_fundings, only: %w(index show new create)
  resources :revenues, only: %w(new create)
  resources :posting_rules
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Budget" %></title><!-- Rails.env: <%= Rails.env %> -->

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Notre Budget", root_url %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="<%= active_if :memo_accounts %>"><%= link_to t("nav.memo_accounts"), memo_accounts_url %></li>

      <li class="has-dropdown <%= active_if :transactions %>">
      <a href="#"><%= t("nav.transactions.label") %></a>
      <ul class="dropdown">
        <li><%= link_to t("nav.transactions.index"), transactions_url %></li>
        <li><%= link_to t("nav.transactions.new"), new_transaction_url %></li>
        <li class="divider"></li>
        <li><%= link_to t("nav.transactions.graph"), graph_transactions_url %></li>
      </ul>
      </li>

      <li class="has-dropdown <%= active_if :bank_transactions %>">
      <a href="#"><%= t("nav.bank_transactions.label") %></a>
      <ul class="dropdown">
        <li><%= link_to t("nav.bank_transactions.index"), bank_transactions_url %></li>
        <li><%= link_to t("nav.bank_transactions.import"), new_bank_transactions_import_url %></li>
      </ul>
      </li>
      <li class="<%= active_if :accounts %>"><%= link_to t("nav.accounts"), accounts_url %></li>
      <li class="<%= active_if :reconciliations %>"><%= link_to t("nav.reconciliations"), reconciliations_url %></li>
      <li class="<%= active_if :liability_fundings %>"><%= link_to t("nav.liability_fundings"), liability_fundings_url %></li>
      <li class="has-dropdown <%= active_if :reveneus, :posting_rules %>">
      <a href="#"><%= t("nav.revenues.label") %></a>
      <ul class="dropdown">
        <li class="<%= active_if :posting_rules %>"><%= link_to t("nav.revenues.posting_rules"), posting_rules_url %></li>
        <li class="<%= active_if :revenues %>"><%= link_to t("nav.revenues.new_revenue"), new_revenue_url %></li>
      </ul>
      </li>
    </ul>
  </section>
</nav>

<div class="container">
  <% if flash[:error] then %>
    <div class="row">
      <div class="small-9 small-centered columns">
        <div class="alert-box alert radius">
          <p><%= flash_message_with_link :error %></p>
        </div>
      </div>
    </div>
  <% end %>
  <% if flash[:notice] then %>
    <div class="row">
      <div class="small-9 small-centered columns">
        <div class="alert-box success radius">
          <p><%= flash_message_with_link :notice %></p>
        </div>
      </div>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>